modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-dimensionlink/issues"
license = "ARR"

[[mods]]
modId = "dimensionlink"
version = "${version}"
displayName = "Dimension Link"
authors = "mahmudindev"
description = '''
Create portal link between dimensions to make custom world sets.
'''
logoFile = "assets/dimensionlink/icon.png"

[[dependencies.dimensionlink]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensionlink]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dimensionlink.mixins.json"
